parameters:
  ServiceConnection: string
  SecretName: string
  SecretValue: string
  KeyVaultName: string

steps:

- task: AzurePowerShell@5
  displayName: 'Write Azure Key Vault Secret ${{ parameters.SecretName }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    ScriptType: InlineScript
    Inline: |
     Add-Type -AssemblyName System.Web

     $password = [System.Web.Security.Membership]::GeneratePassword(16,4)

     $ExistingSecret = Get-AzKeyVaultSecret -VaultName ${{ parameters.KeyVaultName }} -Name ${{ parameters.SecretName }}

     if (-not ([string]::IsNullOrEmpty($ExistingSecret)))
     {
         Write-Host "Secret with name [${{ parameters.SecretName }}] already exists"
     }
     else {
         $Secret = ConvertTo-SecureString -String $password -AsPlainText -Force
         Set-AzKeyVaultSecret -VaultName ${{ parameters.KeyVaultName }} -Name ${{ parameters.SecretName }} -SecretValue $Secret
     }     
    azurePowerShellVersion: LatestVersion