parameters:
  ServiceConnection: string
  KeyVaultName: string
  SecretName: string
  ServiceReleased: string

steps:

- task: AzureKeyVault@1
  displayName: 'Getting Key Vault Secret for ${{ parameters.ServiceReleased }}'
  inputs:
    azureSubscription: ${{ parameters.ServiceConnection }}
    KeyVaultName: ${{ parameters.KeyVaultName }}    
    SecretsFilter: ${{ parameters.SecretName }}     
    RunAsPreJob: false 